myrefuge/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from common.views import HelpView
from refugee.views import RefugeeSignupWizard, RefugeSpaceWishList
from citizen_refuge.views import (CitizenRefugeSignupWizard, CitizenRefugeSpaceList,
                                  CitizenRefugeSpaceDetail, CitizenRefugeSearchView,
                                  CitizenRefugeSpaceApplication, CitizenRefugeMySpaceList,
                                  CitizenRefugeSpaceMessage, CitizenRefugeSpaceApplicationList,
                                  CitizenRefugeSpaceStatus, CitizenRefugeSearchResultView,
                                  CitizenRefugeSpaceEdit, CitizenRefugeSpaceCreate,
                                  LaunchView, LaunchUpdateView)

urlpatterns = [
    url(r'^', include('favicon.urls')),
    url(r'^home/$', 'common.views.home', name='home'),
    url(r'^a7f30687a7805b52c1e8a674434d609626869b13de8a58b7a6f9fc01c0c11db1.txt$', 'common.views.security_scan_file',
        name='security_scan_file'), # support for security scanning
    url(r'^$', CitizenRefugeSearchView.as_view(), name='search_home'),
    url(r'^search/', CitizenRefugeSearchResultView.as_view(), name='search'),
    url(r'^launch/update/$', LaunchUpdateView.as_view(), name='launch_update'),
    url(r'^launch/', LaunchView.as_view(), name='launch'),


    url(r'^accounts/(?P<username>(?!signout|signup|signin)[\@\.\w-]+)/update/'+
                        '(?P<type>(personal|family-delete|family))?/',
        'common.views.profile_update',
        name='profile_update'),
    url(r'^accounts/(?P<username>(?!signout|signup|signin)[\@\.\w-]+)/$',
        'common.views.profile_detail',
        name='userena_profile_detail'),
    
    url(r'^accounts/', include('userena.urls')),
    url(r'^refugee/', RefugeeSignupWizard.as_view(), name='refugee'),
    url(r'^refuge-provider/', CitizenRefugeSignupWizard.as_view(), name='refuge_provider'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^refuge-spaces/me/', CitizenRefugeMySpaceList.as_view(), name='refuge_myspace_list'),
    url(r'^refuge-spaces/create/', CitizenRefugeSpaceCreate.as_view(),
        name='refuge_myspace_create'),
    url(r'^refuge-spaces/(?P<pk>[\.\w-]+)/edit/', CitizenRefugeSpaceEdit.as_view(),
        name='refuge_space_edit'),
    url(r'^refuge-spaces/(?P<pk>[\.\w-]+)/', CitizenRefugeSpaceDetail.as_view(),
        name='refuge_space_detail'),
    url(r'^refuge-spaces/', CitizenRefugeSpaceList.as_view(), name='refuge_space_list'),

    url(r'^bookings/(?P<pk>[\.\w-]+)/compose/', CitizenRefugeSpaceMessage.as_view(),
        name='refuge_space_application_compose'),
    url(r'^bookings/(?P<pk>[\.\w-]+)/update/', CitizenRefugeSpaceStatus.as_view(),
        name='refuge_space_application_update'),
    url(r'^bookings/(?P<pk>(?!all|pending|declined)[\.\w-]+)/',
        CitizenRefugeSpaceApplication.as_view(), name='refuge_space_application'),
    url(r'^bookings/(?P<status>(all|pending|declined))?',
        CitizenRefugeSpaceApplicationList.as_view(), name='refuge_space_application_list'),

    url(r'^wish-list/', RefugeSpaceWishList.as_view(), name='refuge_wish_list'),

    url(r'^help/', HelpView.as_view(), name='myrefuge_help'),


]

apps/citizen_refuge/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.gis.db import models as gis_models
from django.contrib.gis import geos
from django.contrib.sites.models import Site
from django.template.loader import render_to_string

from select_multiple_field.models import SelectMultipleField
from address.models import AddressField
from userena.contrib.umessages.models import Message as BaseMessage

from common.helpers import APPLICATION_STATUS, CITIZEN_SPACE_ADDITIONAL, GENDER, UniqueMediaPath
from common.geo import (address_to_location, location_to_latlon, location_to_city,
                        location_to_country, location_to_public_address, location_to_administrative_area)
from common.mail import send_mass_html_mail
from refugee.models import Refugee

from .managers import CitizenSpaceManager, NGOManager, MessageManager, normalize_name


class CitizenRefuge(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    dob = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER)
    address = AddressField(default="")

    def __repr__(self):
        return '<CitizenRefuge(pk={pk}, user={user})>'.format(pk=self.pk, user=self.user)

    def __unicode__(self):
        return self.__repr__()


class NGO(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField()
    address = AddressField()
    location = gis_models.PointField(u"longitude/latitude",
                                     geography=True, blank=True, null=True)
    email = models.EmailField(max_length=255)
    other = models.CharField(max_length=255, blank=True, null=True)
    charity_no = models.CharField(max_length=255, blank=True, null=True)
    is_christian_org = models.BooleanField(default=False)

    objects = NGOManager()

    def save(self, **kwargs):
        # TODO(hoatle): update location only if address is changed
        # https://github.com/smn/django-dirtyfields
        location = address_to_location(self.address.raw)
        lat, lon = location_to_latlon(location)
        point = 'POINT(%s %s)' % (lon, lat)
        self.location = geos.fromstr(point)
        super(NGO, self).save()

    def __repr__(self):
        return '<NGO(pk={pk}, name="{name}")>'.format(pk=self.pk, name=self.name)

    def __unicode__(self):
        return self.__repr__()


class CitizenSpace(models.Model):
    headline = models.CharField(max_length=255)
    full_description = models.TextField()
    address = AddressField()
    public_address = models.CharField(max_length=255, blank=True)
    # auto set from address field
    city = models.CharField(max_length=255, blank=True, null=True)
    # auto set from address field
    country = models.CharField(max_length=255, blank=True, null=True)
    guests = models.IntegerField(default=0)  # number of guests to be accommodated

    # auto set from address field
    location = gis_models.PointField(u"longitude/latitude",
                                     geography=True, blank=True, null=True)

    additional = SelectMultipleField(max_length=10, choices=CITIZEN_SPACE_ADDITIONAL)

    citizen = models.ForeignKey(CitizenRefuge)

    objects = CitizenSpaceManager()

    def save(self, **kwargs):
        # TODO(hoatle): update location only if address is changed
        # https://github.com/smn/django-dirtyfields
        location = address_to_location(self.address.raw)

        self.public_address = location_to_public_address(location)

        lat, lon = location_to_latlon(location)
        point = 'POINT(%s %s)' % (lon, lat)
        self.location = geos.fromstr(point)

        city = location_to_city(location)
        if city is not None:
            # save ascii lower case no white space only
            self.city = normalize_name(city)

        country = location_to_country(location)
        if country is not None:
            # save ascii lower case no white space only
            self.country = normalize_name(country)

        super(CitizenSpace, self).save()

    def __repr__(self):
        return '<CitizenSpace(pk={pk}, headline="{headline}")>'.format(pk=self.pk,
                                                                       headline=self.headline)

    def __unicode__(self):
        return self.__repr__()


class DateRange(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    space = models.ForeignKey(CitizenSpace)


class SpacePhoto(models.Model):
    image = models.ImageField(upload_to=UniqueMediaPath('space_photos'))
    space = models.ForeignKey(CitizenSpace)


class Application(models.Model):
    refugee = models.ForeignKey(Refugee)
    space = models.ForeignKey(CitizenSpace)
    start_date = models.DateField()
    end_date = models.DateField()
    guests = models.IntegerField(default=0)
    story = models.TextField(blank=True)
    status = models.CharField(
        max_length=1,
        choices=APPLICATION_STATUS,
        default='P',
    )


class Message(BaseMessage):
    application = models.ForeignKey(Application)

    objects = MessageManager()


class Launch(models.Model):
    start_date = models.DateTimeField()


def email_ngos(ngos, space):
    """send emails to nearby ngos to a new created space"""
    data_list = []
    email_from = settings.DEFAULT_FROM_EMAIL
    custom_headers = attachments = None
    for ngo in ngos:
        context = {
            'ngo': ngo,
            'space': space,
            'site': Site.objects.get_current(),
            'area': location_to_administrative_area(address_to_location(space.address.raw))
        }

        subject = render_to_string('citizen_refuge/emails/ngo_email_subject.txt', context)
        subject = ''.join(subject.splitlines())
        msg_plain = render_to_string('citizen_refuge/emails/ngo_email_message.txt', context)
        msg_html = render_to_string('citizen_refuge/emails/ngo_email_message.html', context)
        data_list.append((subject, msg_plain, msg_html, email_from, [ngo.email], custom_headers, attachments))

    send_mass_html_mail(tuple(data_list))


@receiver(post_save, sender=CitizenSpace)
def notify_nearby_ngos_on_space_created(sender, instance, created, **kwargs):
    if created:
        ngos = NGO.objects.find_nearby(instance)
        email_ngos(ngos, instance)

citizen_refuge/models.py
from django.db import models

from address.models import AddressField
from common.helpers import APPLICATION_STATUS, CITIZEN_REFUGE_ADDITIONAL
from common.models import UserProfile
from photologue.models import Gallery
from refugee.models import Refugee
from select_multiple_field.models import SelectMultipleField

# Create your models here.
class CitizenRefuge(UserProfile):
    address = AddressField()
    num_beds = models.IntegerField()
    pictures = models.OneToOneField(Gallery)
    additional = SelectMultipleField(
        max_length=10,
        choices=CITIZEN_REFUGE_ADDITIONAL,
    )

class DateRange(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    citizen = models.ForeignKey(CitizenRefuge)

class Application(models.Model):
    refugee = models.OneToOneField(Refugee)
    citizen = models.OneToOneField(CitizenRefuge)
    status = models.CharField(
        max_length=1,
        choices=APPLICATION_STATUS,
    )

apps/citizen_refuge/forms.py
from django import forms
from userena.forms import EditProfileForm, SignupForm
from django.forms.models import inlineformset_factory, formset_factory
from address.forms import AddressField

from .models import CitizenRefuge, CitizenSpace, DateRange, SpacePhoto, Application, Launch
from common.helpers import CITIZEN_SPACE_ADDITIONAL_SHORT, APPLICATION_STATUS


class CitizenSignupBasicForm(SignupForm):
    pass

class CitizenRefugeAboutForm(forms.ModelForm):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    dob = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                          input_formats=('%d/%m/%Y',))
    mugshot = forms.ImageField()
    agree = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super(CitizenRefugeAboutForm, self).__init__(*args, **kwargs)
        self.fields['agree'].initial = False
        if self.instance.pk:
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name

    def save(self, *args, **kwargs):
        # If we're creating an entirely new citizen, there's logic elsewhere
        # to deal with first and last name.
        citizen = super(CitizenRefugeAboutForm, self).save(*args, **kwargs)
        if self.instance.pk is None:
            return citizen

        user = citizen.user
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return citizen

    class Meta:
        model = CitizenRefuge
        fields = ('dob', 'gender', 'address')

class CitizenRefugePersonalDetailForm(CitizenRefugeAboutForm):
    mugshot = forms.ImageField(required=False)
    agree = forms.BooleanField(required=False)
    address = AddressField(required=False)

class CitizenRefugePersonalImageForm(forms.ModelForm):
    mugshot = forms.ImageField()

    def save(self, *args, **kwargs):
        citizen = super(CitizenRefugePersonalImageForm, self).save(commit=False)
    
        if self.instance.pk is None:
            return citizen

        if self.cleaned_data.get('mugshot'):
            user = citizen.user
            user.my_profile.mugshot = self.cleaned_data.get('mugshot')
            user.my_profile.save()

        return citizen

    class Meta:
        model = CitizenRefuge
        fields = ('mugshot', )


class DateCorrectForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                          input_formats=('%d/%m/%Y',))

    end_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                          input_formats=('%d/%m/%Y',))


from django.forms.widgets import ClearableFileInput

class CustomImageFieldWidget(ClearableFileInput):
    template_with_clear = '%(clear)s <label class="sr-only" for="%(clear_checkbox_id)s">%(clear_checkbox_label)s</label>'

class CitizenRefugeImageForm(forms.Form):
    image = forms.ImageField()


CitizenRefugeSpaceFormset = inlineformset_factory(CitizenRefuge, CitizenSpace,
    fields=('headline', 'address', 'guests', 'full_description', 'additional'),
    extra=0, min_num=1, validate_min=True)

CitizenRefugeDatesFormset = inlineformset_factory(
    CitizenSpace,
    DateRange,
    form=DateCorrectForm,
    fields=('start_date', 'end_date'),
    extra=0, min_num=1, validate_min=True)

SpacePhotoFormset = inlineformset_factory(
    CitizenSpace,
    SpacePhoto,
    fields=('image',),
    extra=0, min_num=1, validate_min=True, max_num=20)


class CitizenRefugeSpaceForm(forms.ModelForm):
    additional = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                         choices=CITIZEN_SPACE_ADDITIONAL_SHORT)
    guests = forms.IntegerField(min_value=0)


    class Meta:
        model = CitizenSpace
        fields = ('headline', 'address', 'guests', 'full_description', 'additional')


class CitizenRefugeeSearchForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                          input_formats=('%d/%m/%Y',), required=False)

    end_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                          input_formats=('%d/%m/%Y',), required=False)

    class Meta:
        model = CitizenSpace

        fields = ('address', 'guests')

class ApplicationForm(forms.ModelForm):

    start_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                          input_formats=('%d/%m/%Y',))

    end_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                          input_formats=('%d/%m/%Y',))

    guests = forms.IntegerField(initial=1)

    class Meta:
        model = Application

        fields = ('start_date', 'end_date', 'guests', )


class ApplicationUpdateForm(forms.ModelForm):

    story = forms.CharField()

    def clean_story(self):
        val = self.cleaned_data.get('story', '').strip()
        if val == "":
            raise forms.ValidationError('Story must not empty')
        return val

    class Meta:
        model = Application

        fields = ('story', )

class ApplicationMessageForm(forms.ModelForm):

    message = forms.CharField()

    def clean_message(self):
        val = self.cleaned_data.get('message', '').strip()
        if val == "":
            raise forms.ValidationError('Message must not empty')
        return val

    class Meta:
        model = Application

        fields = ('message', )

class ApplicationStatusForm(forms.ModelForm):

    status = forms.ChoiceField(choices=APPLICATION_STATUS)

    class Meta:
        model = Application

        fields = ('status', )


class LaunchForm(forms.ModelForm):
    class Meta:
        model = Launch

        fields = ('start_date', )

apps/citizen_refuge/templates/citizen_refuge/about.html
{% extends "base.html" %}
{% load i18n sekizai_tags staticfiles %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block title %}MyRefuge - {% trans "Personal details" %}{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<div id="account">
	<div class="white-sheet">
		<h4 class="title">{% trans "Tell us about yourself" %}</h4>

		<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
			{{ wizard.management_form }}
			{% if wizard.form.forms %}
				{{ wizard.form.management_form }}
				{% for form in wizard.form.forms %}
					{{ form }}
				{% endfor %}
			{% else %}
				{% include "form/input.html" with field=wizard.form.first_name label=wizard.form.first_name.label required=wizard.form.fields.first_name.required %}
				{% include "form/input.html" with field=wizard.form.last_name label=wizard.form.last_name.label required=wizard.form.fields.last_name.required %}
				{% include "form/input.html" with field=wizard.form.dob label="Date of Birth" type="hidden" sr=False name="about-dob_" required=wizard.form.fields.dob.required class="date-block right" %}
				{% include "form/select.html" with field=wizard.form.gender required=wizard.form.fields.gender.required %}
				{% include "form/input.html" with field=wizard.form.address label=wizard.form.address.label required=wizard.form.fields.address.required  %}
				
				{% include "form/input.html" with field=wizard.form.mugshot label="Photo" sr=False %}
				{% include "form/checkbox.html" with field=wizard.form.agree label='I agree to the terms and conditions <a href="#" data-toggle="modal" data-target="#term"><i class="dark fa fa-info-circle"></i></a>' %}
				
			{% endif %}

			<input class="btn btn-block btn-primary" type="submit" value="{% trans "Register" %}"/>
		</form>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="term" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Terms &amp; Conditions</h4>
      </div>
      <div class="modal-body help-text">
        <ol>
			<li>We will not share your personal information with anyone</li>
			<li>In providing shelter, we will give you the option to connect with or be contacted by relevant services or authorities as and when needed in processes of asylum</li>
			<li>MyRefuge is providing a matchmaking service. You agree to abide by the laws of relevant countries with regards to Asylum.</li>
        </ol>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block js_ %}
    <script src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false" type="text/javascript"></script>
    <script src="{% static "js/jquery.geocomplete.min.js" %}" type="text/javascript"></script>
    <script src="{% static "address/js/address.js" %}" type="text/javascript"></script>
    <script type="text/javascript">
        (function () {
			whenAvailable('google', function() {
				$("#id_about-address").geocomplete();
			});
			
			$(function() {
                $("#id_about-dob").dateDropdowns({
					submitFormat: "dd/mm/yyyy",
					submitFieldName: "about-dob",
					defaultDateFormat: "dd/mm/yyyy",
					wrapperClass: "date-dropdowns inline",
					minYear: 1915,
					defaultDate: $("#id_about-dob").val()
				});
            });
			
		})();
    </script>
{% endblock %}

apps/citizen_refuge/templates/citizen_refuge/application_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load url from future %}
{% load common_filters %}

{% block title %}{% trans "Booked spaces" %}{% endblock %}


{% block content %}
<div class="container">
    <div class="container-inner narrow">
        <h1 class="entry-title">
          {% trans "My Requests" %}
        </h1>
        {% if application_list %}
        <div class="booking-list border-top">
          <ul class="media-list">
            {% for application in application_list %}
              <li class="media">
                <div class="media-left media-middle">
                    <a class="media-inner" href="{% url 'userena_profile_detail' application.space.citizen.user %}">
                        <img class="media-object img-circle" src="{{application.space.citizen.user.my_profile.get_mugshot_url}}" alt="{{ application.space.citizen.user.first_name }}">
                    </a>
                </div>
                <div class="media-body">
                  <p>{% trans "The request is: " %}<a href="{% url 'refuge_space_application' application.id %}" class="text status {{application.status}}">{{status_list|get_item:application.status}}</a></p>
                    {{application.story|slice:":40"|safe|linebreaks}}
                    <p class="media-subtitle"><strong>Space: </strong><a href="{% url 'refuge_space_detail' application.space.id %}">{{application.space.headline}}</a></h4>
                    <p class="media-subtitle"><strong>At: </strong>{{application.space.city}}, {{application.space.country}}</h4>
                </div>
              </li>
            {% endfor %}
          </ul>
        </div>
        {% else %}
        <p>{% trans "No booked space!" %}</p>
        {% endif %}

        {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{% url 'refuge_wish_list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{% url 'refuge_wish_list' %}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
              </span>
          </div>
        {% endif %}
    </div>
</div>
{% endblock %}

apps/citizen_refuge/templates/citizen_refuge/citizenspace_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load url from future %}
{% load common_filters %}
{% load i18n sekizai_tags staticfiles %}
{% load leaflet_tags %}


{% block title %}{% blocktrans with citizenspace.citizen.user.username as username %}{{ username }}'s refuge spaces.{% endblocktrans %}{% endblock %}

{% block body_class %}space{% endblock %}


{% block css_ %}
<link rel="stylesheet" href="{% static "bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" %}" />
{% leaflet_css %}
{% endblock %}

{% block content %}
<div class="space-banner" style="background-image: url({{citizenspace.spacephoto_set.all.0.image.url}});"></div>
<div class="container">
    <div class="container-inner">
      <div class="row">
        <div class="col-md-8">
          <h1 class="entry-title visible-xs">{{ citizenspace.headline }}</h1>
          <div class="media">
            <div class="media-left media-middle">
                <a class="media-inner" href="#">
                    <img class="media-object" src="{{ citizenspace.citizen.user.my_profile.get_mugshot_url }}" alt="{{ citizenspace.citizen.user.first_name }}">
                    {{ citizenspace.citizen.user.first_name }}
                </a>
            </div>
            <div class="media-body">

              <h1 class="entry-title hidden-xs">{{ citizenspace.headline }}</h1>
              <div class="row space-info">
                <div class="col-sm-2 space-item">
                  <i class="fa fa-bed"></i><br>
                  {{ citizenspace.guests }} guest(s)
                </div>
                {% for ad in citizenspace.additional%}
                  <div class="col-sm-2 space-item">
                    <i class="fa fa-{{ space_list_icon|get_item:ad }}"></i><br>
                    {{ space_list|get_item:ad }}
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-6">
              <p>
                <strong>Availabilities:</strong><br>
                {% for daterange in citizenspace.daterange_set.all %}
                From <strong>{{ daterange.start_date }}</strong> to <strong>{{ daterange.end_date }}</strong>
                {% if not forloop.last %}<br>{% endif %}
                {% endfor %}
              </p>
            </div>
            <div class="col-sm-6">
              <strong>Location:</strong><br>
              <p>{{ citizenspace.public_address }}</p>
            </div>
          </div>
          
          <hr>
          <h3 class="entry-subtitle">Description</h3>
          <p>{{ citizenspace.full_description|safe|linebreaks }}</p>
          <hr>
          <h3 class="entry-subtitle">Photos</h3>
          <p class="space-photos">
          {% for photo in citizenspace.spacephoto_set.all %}
              <a href="{{photo.image.url}}" target="__blank"><img src="{{photo.image.url}}" alt="{{ profile.user.username }}"></a>
          {% endfor %}
          </p>

        </div>
        <div class="col-md-4">
          {% leaflet_map "provider-places" %}
          <br>
          {% if can_edit %}
            <p><a class="btn btn-primary" href="{% url 'refuge_space_edit' citizenspace.id %}"><strong>Edit space</strong></a></p>
          {% endif %}

          {% if form %}
          <form method="post" class="application-form">
            {% csrf_token %}
            {% include "form/checkin-block.html" with form=form guests=citizenspace.guests %}
            <div class="clearfix dv"></div>
            <button type="submit" class="btn btn-secondary btn-block btn-lg" {% if not site_ready %}disabled{% endif %}>Request to Book</button>
            {% if not site_ready %}<p class="help-text red"><br>{% trans "We aim to enable this button by 10 October 2015" %}</p>{% endif %}
          </form>
          {% else%}
            {% if user.my_profile.type == 'R' %}
              <p><b>Your request has been sent!</b> <a href="{% url 'refuge_space_application' application.id %}">View messages.</a></p>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
</div>
{% endblock %}



{% block js_ %}
    {% leaflet_js %}
    <script src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false" type="text/javascript"></script>
    <script src="{% static "js/jquery.geocomplete.min.js" %}" type="text/javascript"></script>
    <script src="{% static "address/js/address.js" %}" type="text/javascript"></script>
    <script src="{% static "bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" %}" type="text/javascript"></script>

    <script type="text/javascript">
        (function () {
            $(function() {
                var $from = $('.form-group.from input'),
                    $to = $('.form-group.to input');
                 
                $from.datepicker({
                        format: 'dd/mm/yyyy',
                        startDate: '0d'
                    })
                    .on('changeDate', function(ev) {
                        if (ev.date.valueOf() > checkout.viewDate.valueOf()) {
                            checkout.setStartDate(ev.date);
                        }
                        checkin.hide();
                        $to.focus();
                    });

                $to.datepicker({
                        format: 'dd/mm/yyyy',
                        startDate: '1d'
                    })
                    .on('changeDate', function(ev) {
                        checkout.hide();
                    });

                var checkin = $from.data('datepicker'),
                    checkout = $to.data('datepicker');
            });
            $(window).on('map:init', function (e) {
                var detail = e.originalEvent ?
                             e.originalEvent.detail : e.detail,
                    map = detail.map,
                    loc = null;

                {% random_coords citizenspace.location.y citizenspace.location.x as coords %}
                var coords = [{{coords.0}}, {{coords.1}}];

                {% if citizenspace.citizen.user == user or citizenspace|has_been_accepted:user %}
                  coords = [{{citizenspace.location.y}}, {{citizenspace.location.x}}];
                {% endif %}

                map.setView(coords, 13);
                L.marker(coords).addTo(map);
            });
        })();
        
    </script>

{% endblock %}

apps/citizen_refuge/templates/citizen_refuge/space-block.html
{% load i18n %}
{% load url from future %}
{% load common_filters %}

<div class="thumbnail flat" id="space-{{space.id}}">
  <a href="{% if href %}{% url href id %}{% else %}{% url 'refuge_space_detail' space.id %}{% endif %}">
    <img class="img-full" src="{{space.spacephoto_set.all.0.image.url}}" alt="{{ space.headline }}" style="background-image: url({{space.spacephoto_set.all.0.image.url}});">
  </a>
  <div class="caption">
    <h3><a href="{% if href %}{% url href id %}{% else %}{% url 'refuge_space_detail' space.id %}{% endif %}">{{space.headline}}</a></h3>
    <p>
      {{space.public_address}}
    </p>

  </div>
  <footer class="footer">
    <strong>Availabilities</strong>
    <p>
      {% for daterange in space.daterange_set.all %}
        From <strong>{{ daterange.start_date }}</strong> to <strong>{{ daterange.end_date }}</strong>
        {% if not forloop.last %}<br>{% endif %}
      {% endfor %}
    </p>
  </footer>
</div>