myrefuge/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from common.views import HelpView
from refugee.views import RefugeeSignupWizard, RefugeSpaceWishList
from citizen_refuge.views import (CitizenRefugeSignupWizard, CitizenRefugeSpaceList,
                                  CitizenRefugeSpaceDetail, CitizenRefugeSearchView,
                                  CitizenRefugeSpaceApplication, CitizenRefugeMySpaceList,
                                  CitizenRefugeSpaceMessage, CitizenRefugeSpaceApplicationList,
                                  CitizenRefugeSpaceStatus, CitizenRefugeSearchResultView,
                                  CitizenRefugeSpaceEdit, CitizenRefugeSpaceCreate,
                                  LaunchView, LaunchUpdateView)

urlpatterns = [
    url(r'^', include('favicon.urls')),
    url(r'^home/$', 'common.views.home', name='home'),
    url(r'^a7f30687a7805b52c1e8a674434d609626869b13de8a58b7a6f9fc01c0c11db1.txt$', 'common.views.security_scan_file',
        name='security_scan_file'), # support for security scanning
    url(r'^$', CitizenRefugeSearchView.as_view(), name='search_home'),
    url(r'^search/', CitizenRefugeSearchResultView.as_view(), name='search'),
    url(r'^launch/update/$', LaunchUpdateView.as_view(), name='launch_update'),
    url(r'^launch/', LaunchView.as_view(), name='launch'),


    url(r'^accounts/(?P<username>(?!signout|signup|signin)[\@\.\w-]+)/update/'+
                        '(?P<type>(personal|family-delete|family))?/',
        'common.views.profile_update',
        name='profile_update'),
    url(r'^accounts/(?P<username>(?!signout|signup|signin)[\@\.\w-]+)/$',
        'common.views.profile_detail',
        name='userena_profile_detail'),
    
    url(r'^accounts/', include('userena.urls')),
    url(r'^refugee/', RefugeeSignupWizard.as_view(), name='refugee'),
    url(r'^refuge-provider/', CitizenRefugeSignupWizard.as_view(), name='refuge_provider'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^refuge-spaces/me/', CitizenRefugeMySpaceList.as_view(), name='refuge_myspace_list'),
    url(r'^refuge-spaces/create/', CitizenRefugeSpaceCreate.as_view(),
        name='refuge_myspace_create'),
    url(r'^refuge-spaces/(?P<pk>[\.\w-]+)/edit/', CitizenRefugeSpaceEdit.as_view(),
        name='refuge_space_edit'),
    url(r'^refuge-spaces/(?P<pk>[\.\w-]+)/', CitizenRefugeSpaceDetail.as_view(),
        name='refuge_space_detail'),
    url(r'^refuge-spaces/', CitizenRefugeSpaceList.as_view(), name='refuge_space_list'),

    url(r'^bookings/(?P<pk>[\.\w-]+)/compose/', CitizenRefugeSpaceMessage.as_view(),
        name='refuge_space_application_compose'),
    url(r'^bookings/(?P<pk>[\.\w-]+)/update/', CitizenRefugeSpaceStatus.as_view(),
        name='refuge_space_application_update'),
    url(r'^bookings/(?P<pk>(?!all|pending|declined)[\.\w-]+)/',
        CitizenRefugeSpaceApplication.as_view(), name='refuge_space_application'),
    url(r'^bookings/(?P<status>(all|pending|declined))?',
        CitizenRefugeSpaceApplicationList.as_view(), name='refuge_space_application_list'),

    url(r'^wish-list/', RefugeSpaceWishList.as_view(), name='refuge_wish_list'),

    url(r'^help/', HelpView.as_view(), name='myrefuge_help'),


]

apps/citizen_refuge/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.gis.db import models as gis_models
from django.contrib.gis import geos
from django.contrib.sites.models import Site
from django.template.loader import render_to_string

from select_multiple_field.models import SelectMultipleField
from address.models import AddressField
from userena.contrib.umessages.models import Message as BaseMessage

from common.helpers import APPLICATION_STATUS, CITIZEN_SPACE_ADDITIONAL, GENDER, UniqueMediaPath
from common.geo import (address_to_location, location_to_latlon, location_to_city,
                        location_to_country, location_to_public_address, location_to_administrative_area)
from common.mail import send_mass_html_mail
from refugee.models import Refugee

from .managers import CitizenSpaceManager, NGOManager, MessageManager, normalize_name


class CitizenRefuge(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    dob = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER)
    address = AddressField(default="")

    def __repr__(self):
        return '<CitizenRefuge(pk={pk}, user={user})>'.format(pk=self.pk, user=self.user)

    def __unicode__(self):
        return self.__repr__()


class NGO(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField()
    address = AddressField()
    location = gis_models.PointField(u"longitude/latitude",
                                     geography=True, blank=True, null=True)
    email = models.EmailField(max_length=255)
    other = models.CharField(max_length=255, blank=True, null=True)
    charity_no = models.CharField(max_length=255, blank=True, null=True)
    is_christian_org = models.BooleanField(default=False)

    objects = NGOManager()

    def save(self, **kwargs):
        # TODO(hoatle): update location only if address is changed
        # https://github.com/smn/django-dirtyfields
        location = address_to_location(self.address.raw)
        lat, lon = location_to_latlon(location)
        point = 'POINT(%s %s)' % (lon, lat)
        self.location = geos.fromstr(point)
        super(NGO, self).save()

    def __repr__(self):
        return '<NGO(pk={pk}, name="{name}")>'.format(pk=self.pk, name=self.name)

    def __unicode__(self):
        return self.__repr__()


class CitizenSpace(models.Model):
    headline = models.CharField(max_length=255)
    full_description = models.TextField()
    address = AddressField()
    public_address = models.CharField(max_length=255, blank=True)
    # auto set from address field
    city = models.CharField(max_length=255, blank=True, null=True)
    # auto set from address field
    country = models.CharField(max_length=255, blank=True, null=True)
    guests = models.IntegerField(default=0)  # number of guests to be accommodated

    # auto set from address field
    location = gis_models.PointField(u"longitude/latitude",
                                     geography=True, blank=True, null=True)

    additional = SelectMultipleField(max_length=10, choices=CITIZEN_SPACE_ADDITIONAL)

    citizen = models.ForeignKey(CitizenRefuge)

    objects = CitizenSpaceManager()

    def save(self, **kwargs):
        # TODO(hoatle): update location only if address is changed
        # https://github.com/smn/django-dirtyfields
        location = address_to_location(self.address.raw)

        self.public_address = location_to_public_address(location)

        lat, lon = location_to_latlon(location)
        point = 'POINT(%s %s)' % (lon, lat)
        self.location = geos.fromstr(point)

        city = location_to_city(location)
        if city is not None:
            # save ascii lower case no white space only
            self.city = normalize_name(city)

        country = location_to_country(location)
        if country is not None:
            # save ascii lower case no white space only
            self.country = normalize_name(country)

        super(CitizenSpace, self).save()

    def __repr__(self):
        return '<CitizenSpace(pk={pk}, headline="{headline}")>'.format(pk=self.pk,
                                                                       headline=self.headline)

    def __unicode__(self):
        return self.__repr__()


class DateRange(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    space = models.ForeignKey(CitizenSpace)


class SpacePhoto(models.Model):
    image = models.ImageField(upload_to=UniqueMediaPath('space_photos'))
    space = models.ForeignKey(CitizenSpace)


class Application(models.Model):
    refugee = models.ForeignKey(Refugee)
    space = models.ForeignKey(CitizenSpace)
    start_date = models.DateField()
    end_date = models.DateField()
    guests = models.IntegerField(default=0)
    story = models.TextField(blank=True)
    status = models.CharField(
        max_length=1,
        choices=APPLICATION_STATUS,
        default='P',
    )


class Message(BaseMessage):
    application = models.ForeignKey(Application)

    objects = MessageManager()


class Launch(models.Model):
    start_date = models.DateTimeField()


def email_ngos(ngos, space):
    """send emails to nearby ngos to a new created space"""
    data_list = []
    email_from = settings.DEFAULT_FROM_EMAIL
    custom_headers = attachments = None
    for ngo in ngos:
        context = {
            'ngo': ngo,
            'space': space,
            'site': Site.objects.get_current(),
            'area': location_to_administrative_area(address_to_location(space.address.raw))
        }

        subject = render_to_string('citizen_refuge/emails/ngo_email_subject.txt', context)
        subject = ''.join(subject.splitlines())
        msg_plain = render_to_string('citizen_refuge/emails/ngo_email_message.txt', context)
        msg_html = render_to_string('citizen_refuge/emails/ngo_email_message.html', context)
        data_list.append((subject, msg_plain, msg_html, email_from, [ngo.email], custom_headers, attachments))

    send_mass_html_mail(tuple(data_list))


@receiver(post_save, sender=CitizenSpace)
def notify_nearby_ngos_on_space_created(sender, instance, created, **kwargs):
    if created:
        ngos = NGO.objects.find_nearby(instance)
        email_ngos(ngos, instance)

apps/refugee/views.py
import os
from formtools.wizard.views import SessionWizardView
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django_countries import countries

from userena.forms import SignupForm
from userena.models import UserenaSignup
from userena import signals as userena_signals
from common.forms import UserenaEditProfileForm
from .forms import *
from .models import Refugee, FamilyMember
from citizen_refuge.models import Application
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import ProcessFormView
from common.helpers import GENDER, APPLICATION_STATUS
from django.core.exceptions import PermissionDenied

KEYS = ['userena', 'basic', 'family', 'address', 'country']
FORMS = [SignupForm, RefugeeSignUpBasic, FamilyMemberFormset, RefugeeSignUpAddress, RefugeeSignUpPreferences]
FORM_LIST = zip(KEYS, FORMS)
TEMPLATES = dict(zip(KEYS, ['refugee/' + k + '.html' for k in KEYS]))

def skip_family(wizard):
    """Return true if user opts to pay by credit card"""
    cleaned_data = wizard.storage.get_step_data('basic') or {'skip_family': '0'}
    return cleaned_data.get('skip_family', '0') != '1'

class RefugeeSignupWizard(SessionWizardView):
    form_list = FORM_LIST
    file_storage = FileSystemStorage(location='/tmp/')

    instance_dict = {
        'family': FamilyMember.objects.none()
    }

    condition_dict = {
        'family': skip_family
    }

    def __init__(self, *args, **kwargs):
        super(RefugeeSignupWizard, self).__init__(*args, **kwargs)

    def done(self, form_list, form_dict, **kwargs):
        # Create the user
        user = form_dict['userena'].save()
        mugshot = form_dict['basic'].cleaned_data.get('mugshot')
        user.my_profile.mugshot = mugshot
        user.my_profile.type = 'R'
        user.my_profile.save()

        # Set first and last name on user
        basic = form_dict['basic']
        user.first_name = basic.cleaned_data.get('first_name')
        user.last_name = basic.cleaned_data.get('last_name')
        user.save()

        # Concatenate all the information from the forms and save.
        refugee = Refugee(user=user)
        family_members = []
        for key in form_dict:
            if key == 'userena': continue
            form = form_dict[key]
            if key == 'family':
                for dataset in form.cleaned_data:
                    if len(dataset):
                        family_members.append(FamilyMember(**dataset))

            else:
                for field in form.cleaned_data.keys():
                    if field == 'mugshot': continue
                    setattr(refugee, field, form.cleaned_data[field])

        refugee.save()
        for member in family_members:
            member.refugee = refugee
            member.save()

        return HttpResponseRedirect(reverse('userena_signup_complete', kwargs={'username': user.username}))

    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

class RefugeSpaceWishList(ListView):
    model = Application
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.my_profile.type == 'R':
            return self.model._default_manager.filter(refugee=self.request.user.refugee)

        return self.model._default_manager.none()

    def get_context_data(self, **kwargs):
        context = super(RefugeSpaceWishList, self).get_context_data(**kwargs)
        context['status_list'] = APPLICATION_STATUS

        return context

class RefugeDetail(TemplateView):
    template_name = 'common/profile_detail.html'

    def post(self, request, *args, **kwargs):
        form = RefugeFamilyCreateForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        member = form.save(commit=False)
        member.refugee = self.request.user.refugee
        member.save()
        return self.render_to_response(self.get_context_data())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, form=None, **kwargs):
        context = super(RefugeDetail, self).get_context_data(**kwargs)
        context['profile'] = self.request.user.my_profile
        if hasattr(self.request.user, 'refugee'):
            context['citizen'] = self.request.user.refugee
            context['family_members'] = self.request.user.refugee.\
                                            familymember_set.order_by('pk').all()
            context['family_form'] = form or RefugeFamilyCreateForm()
        context['gender_list'] = GENDER[1:]
        context['countries_list'] = countries
        return context

class RefugeDetailUpdate(ProcessFormView):
    template_name = 'common/profile_detail.html'

    def get(self, request, *args, **kwargs):
        raise PermissionDenied

    def post(self, request, *args, **kwargs):
        if self.kwargs.get('type') == 'family':
            family = FamilyMember.objects.filter(pk=self.request.POST.get('id'),
                        refugee=self.request.user.refugee).first()
            if len(self.request.FILES):
                form = RefugeFamilyImageForm(self.request.POST, self.request.FILES,
                        instance=family)
            else:
                form = RefugeFamilyCreateForm(self.request.POST, instance=family)

        elif self.kwargs.get('type') == 'family-delete':
            family = FamilyMember.objects.filter(pk=self.request.POST.get('id'),
                        refugee=self.request.user.refugee).first()
            if family:
                family.delete()
                return JsonResponse({'success': True})
            return JsonResponse({'success': False})
        else:
            if len(self.request.FILES):
                form = RefugePersonalImageForm(self.request.POST, self.request.FILES,
                        instance=self.request.user.refugee)
            else:
                form = RefugePersonalDetailForm(self.request.POST,
                            instance=self.request.user.refugee)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        if self.kwargs.get('type') == 'family-create':
            member = form.save(commit=False)
            member.refugee = self.request.user.refugee
            member.save()
        else:
            model = form.save(commit=False)
            model.save()

            if hasattr(model, 'user'):
                url = model.user.my_profile.get_mugshot_url()
            elif model.image:
                url = model.image.url
            else:
                url = ''

            if len(self.request.FILES):
                return JsonResponse({'success': True, 'url': url})

        return JsonResponse({'success': True})

    def form_invalid(self, form):
        return JsonResponse({'success': False,'errors': form.errors})

apps/refugee/templates/refugee/address.html
{% extends "base.html" %}
{% load i18n %}
{% load i18n sekizai_tags staticfiles %}

{% block header %}{% endblock %}

{% block content %}
<div id="account">
	<div class="white-sheet">
		<div class="text-center vr-2">
			<strong>
				<!-- Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }} -  -->
				{% trans "Where are you from?" %}
			</strong>
		</div>

		<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
			{{ wizard.management_form }}
			{% if wizard.form.forms %}
				{{ wizard.form.management_form }}
				{% for form in wizard.form.forms %}
					{{ form }}
				{% endfor %}
			{% else %}
				{% include "form/input.html" with field=wizard.form.hometown label=wizard.form.hometown.label required=wizard.form.fields.hometown.required %}
				{% include "form/input.html" with field=wizard.form.full_address label=wizard.form.full_address.label required=wizard.form.fields.full_address.required %}
				{% include "form/input.html" with field=wizard.form.current_address label="Current address (if applicable)" %}
				{% include "form/textarea.html" with field=wizard.form.story label="Your Story (optional)" rows="10" %}
			{% endif %}

			<input class="btn btn-block btn-primary" type="submit" value="{% trans "Next where do you want to go?" %}"/>
		</form>
	</div>
</div>


{% addtoblock "js" %}
	{{ wizard.form.fields.full_address.widget.media }}
    <script type="text/javascript">
        (function () {
			whenAvailable('google', function() {
				$("#id_address-full_address").geocomplete();
				$("#id_address-current_address").geocomplete()
			});
        })();
    </script>
{% endaddtoblock %}

{% endblock %}

apps/refugee/templates/refugee/application_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load url from future %}
{% load common_filters %}

{% block title %}{% trans "Booked spaces" %}{% endblock %}


{% block content %}
<div class="container">
    <div class="container-inner">
        <h1 class="entry-title">
          {% trans "Booked spaces" %}
        </h1>
        <div class="row">
          {% for application in application_list %}
          <div class="col-sm-4">
            {% include "refugee/application-block.html" with application=application %}
          </div>
          {% if forloop.counter|divisibleby:3 and forloop.counter != 0 %}
        </div>
        <div class="row">
          {% endif %}
          {% endfor %}
        </div>

        {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{% url 'refuge_wish_list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{% url 'refuge_wish_list' %}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
              </span>
          </div>
        {% endif %}
    </div>
</div>
{% endblock %}

apps/refugee/templates/refugee/basic.html
{% extends "base.html" %}
{% load i18n sekizai_tags staticfiles %}

{% block title %}MyRefuge - {% trans "Personal details" %}{% endblock %}

{% block header %}{% endblock %}

{% block content %}

<div id="account">
	<div class="white-sheet">
		<h4 class="title">{% trans "Tell us about yourself" %}</h4>

		<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
			{{ wizard.management_form }}
			{% if wizard.form.forms %}
				{{ wizard.form.management_form }}
				{% for form in wizard.form.forms %}
					{{ form }}
				{% endfor %}
			{% else %}
				{% include "form/input.html" with field=wizard.form.first_name label=wizard.form.first_name.label required=wizard.form.fields.first_name.required %}
				{% include "form/input.html" with field=wizard.form.last_name label=wizard.form.last_name.label required=wizard.form.fields.last_name.required %}
				{% include "form/input.html" with field=wizard.form.dob label="Date of Birth" type="hidden" sr=False name="basic-dob_" required=wizard.form.fields.dob.required class="date-block right" %}
				{% include "form/select.html" with field=wizard.form.gender required=wizard.form.fields.gender.required %}
				{% include "form/input.html" with field=wizard.form.mugshot label="Photo" sr=False %}
			{% endif %}

			<button class="btn btn-primary" name="skip_family" type="submit" value="1">{% trans "Traveling on my own. Next" %}</button>
			<button class="btn btn-primary btn-right" type="submit" value="">{% trans "Add family member" %}</button>
		</form>
	</div>
</div>

{% addtoblock "js" %}
	<script type="text/javascript">
		(function () {
			$("#id_basic-dob").dateDropdowns({
				submitFormat: "dd/mm/yyyy",
				submitFieldName: "basic-dob",
				wrapperClass: "date-dropdowns inline",
				defaultDateFormat: "dd/mm/yyyy",
				defaultDate: $("#id_basic-dob").val(),
			});
		})();
	</script>
{% endaddtoblock %}

{% endblock %}

apps/refugee/templates/refugee/country.html
{% extends "base.html" %}
{% load i18n sekizai_tags staticfiles %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block title %}MyRefuge - {% trans "Where to go?" %}{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<div id="account">
    <div class="white-sheet">
        <h4 class="title">{% trans "Where do you want to go?" %}</h4>

        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ wizard.management_form }}
            {% if wizard.form.forms %}
                {{ wizard.form.management_form }}
                {% for form in wizard.form.forms %}
                    {{ form }}
                {% endfor %}
            {% else %}
                {% include "form/select.html" with field=wizard.form.countries label=wizard.form.countries.label multiple=True %}
                
                {% include "form/checkbox.html" with field=wizard.form.agree label=wizard.form.agree.label label='I agree to the terms and conditions <div class="help-text"><ul><li>We will not share your personal information with anyone</li><li>In providing shelter, we will give you the option to connect with or be contacted by relevant services or authorities as and when needed in processes of asylum</li><li>MyRefuge is providing a matchmaking service. You agree to abide by the laws of relevant countries with regards to Asylum.</li></ul></div>' %}
            {% endif %}

            <input class="btn btn-block btn-primary" type="submit" value="{% trans "Finish! Search places!" %}"/>
        </form>
    </div>
</div>


{% addtoblock "js" %}
    <script type="text/javascript">
        (function () {
            // deselect first
            $('#id_country-countries option').attr('selected', false);
            $('#id_country-countries').selectize({
                placeholder: "Country names",
            });
        })();
    </script>
{% endaddtoblock %}

{% endblock %}

apps/refugee/templates/refugee/family.html
{% extends "base.html" %}
{% load i18n sekizai_tags staticfiles %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block title %}MyRefuge - {% trans "Family details" %}{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<div id="account">
	<div class="white-sheet">
		<h4 class="title">{% trans "About your family member" %}</h4>
		<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
			{{ wizard.management_form }}
			<div>
				{% if wizard.form.forms %}
					{{ wizard.form.management_form }}
					<div class="to-clone">
						{% for form in wizard.form.forms %}
						<div class="form-inner">
							{% include "form/input.html" with field=form.name label=form.name.label required=form.fields.name.required %}
							{% include "form/input.html" with field=form.dob label="Date of Birth" type="hidden" sr=False name="family-0-dob_" required=form.fields.dob.required class="date-block right" %}
							{% include "form/select.html" with field=form.gender required=form.fields.gender.required %}
							{% include "form/input.html" with field=form.relationship label=form.relationship.label required=form.fields.relationship.required %}
							{% include "form/input.html" with field=form.image label=form.image.label sr=False label="Photo" %}
						</div>
						{% endfor %}
					</div>
				{% else %}
					{{ wizard.form }}
				{% endif %}
			</div>

			<input class="btn btn-block btn-primary" type="submit" value="{% trans "Finish adding family. Next" %}"/>
		</form>

		{% addtoblock "js" %}
		<script src="{% static "js/jquery.formset.js" %}"></script>
		{% endaddtoblock %}

		{% addtoblock "js" %}
			<script type="text/javascript">
				function createDatepicker(id) {
					/*var picker = new Pikaday({
						field: document.getElementById(id),
						format: 'DD/MM/YYYY',
						minDate: moment("1915-01-01").toDate(),
						maxDate: new Date(),
						yearRange: [1915, 2015]
					});*/

					$('#' + id).dateDropdowns({
						submitFormat: "dd/mm/yyyy",
						submitFieldName: id.replace('id_',''),
						wrapperClass: "date-dropdowns inline",
						minYear: 1915,
						defaultDateFormat: "dd/mm/yyyy",
						defaultDate: $('#' + id).val()
					});
				}

				$(function() {
					$('form .form-inner').formset({
						prefix: '{{ wizard.form.prefix }}',
						addText: 'Add another',
						deleteText: 'Remove',
						addCssClass: 'btn-add-form btn btn-block btn-primary',
						deleteCssClass: 'formset-control vr-1'
					});

					$('.btn-add-form').click(function () {
						var id = $('.form-inner').last().find('.date-block input').attr('id');
						createDatepicker(id);
					});

					$('.date-block input').each(function() {
						createDatepicker($(this).attr('id'));
					});

					
				});
			</script>
		{% endaddtoblock %}
	</div>
</div>
{% endblock %}

apps/refugee/templates/refugee/userena.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block title %}MyRefuge - {% trans "Login details" %}{% endblock %}

{% block header %}{% endblock %}

{% block content %}

<div id="account">
	<div class="white-sheet">
		<div class="text-center vr-2">
			<strong>
				<!-- Step  {{ wizard.steps.step1 }} of {{ wizard.steps.count }} -  -->
				{% trans "Login details" %}
			</strong>
		</div>

		<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
			{{ wizard.management_form }}
			{% if wizard.form.forms %}
				{{ wizard.form.management_form }}
				{% for form in wizard.form.forms %}
					{{ form }}
				{% endfor %}
			{% else %}
				{% include "form/input.html" with field=wizard.form.username label=wizard.form.username.label %}
				{% include "form/input.html" with field=wizard.form.email label=wizard.form.email.label %}
				{% include "form/input.html" with field=wizard.form.password1 label="Password" %}
				{% include "form/input.html" with field=wizard.form.password2 label=wizard.form.password2.label %}
			{% endif %}

			{% include "form/step_btns.html" with steps=wizard.steps %}

			<input class="btn btn-block btn-primary btn-lg" type="submit" value="{% trans "Submit" %}"/>
		</form>
	</div>
</div>

{% endblock %}